language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support

cache:
  directories:
    # Gradle deps (see https://guides.gradle.org/executing-gradle-builds-on-travisci/)
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"

    # Android build cache
    - "$HOME/.android/build-cache/"

script:
  - export GRADLE_OPTS="-Xmx2048m"
  - ./gradlew
      -Pci
      --no-daemon
      --exclude-task signProductionWebsiteRelease
      assembleWebsite
      testWebsiteReleaseUnitTest
