version: '3.2'
services:
  assemble:
    image: reproducible-molly
    build:
      context: ..
    command: :app:assembleRelease :app:bundleRelease
    volumes:
      - ./certs:/molly/app/certs:ro
      - ./outputs:/molly/app/build/outputs
    environment:
      - CI_APP_TITLE
      - CI_APP_FILENAME
      - CI_PACKAGE_ID
      - CI_BUILD_VARIANTS
      - CI_FORCE_INTERNAL_USER_FLAG
      - CI_MAPS_API_KEY
      - CI_KEYSTORE_PATH
      - CI_KEYSTORE_PASSWORD
      - CI_KEYSTORE_ALIAS
  test:
    image: reproducible-molly
    build:
      context: ..
    command: build
    volumes:
      - ./test-reports:/molly/app/build/reports
    environment:
      - BUILD_SCAN=1
    profiles:
      - test
