name: Android CI

on: [ push, pull_request ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-18.04
    env:
      BUILD_SCAN: 1
      ORG_GRADLE_PROJECT_ci: 1
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '8.0.292'
    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: Build and run tests
      run: ./gradlew qa
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: molly-apk
        path: app/build/outputs/apk/**/release/*.apk

  release:
    name: Release
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-18.04
    steps:
    - name: Download release APKs
      uses: actions/download-artifact@v1
      with:
        name: molly-apk
    - name: Get the version
      id: get-version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
    - name: Create release
      id: create-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Molly Android ${{ steps.get-version.outputs.VERSION }}
        draft: true
        prerelease: false
    - name: Upload APK staging
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: ./molly-apk/nonFreeStaging/release/Molly-staging-release-unsigned-${{ steps.get-version.outputs.VERSION }}.apk
        asset_name: Molly-staging-unsigned-${{ steps.get-version.outputs.VERSION }}.apk
        asset_content_type: application/zip
    - name: Upload APK production
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: ./molly-apk/nonFreeProduction/release/Molly-production-release-unsigned-${{ steps.get-version.outputs.VERSION }}.apk
        asset_name: Molly-production-unsigned-${{ steps.get-version.outputs.VERSION }}.apk
        asset_content_type: application/zip
    - name: Upload APK staging OSS
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: ./molly-apk/freeStaging/release/Molly-staging-release-unsigned-${{ steps.get-version.outputs.VERSION }}-FOSS.apk
        asset_name: Molly-staging-unsigned-${{ steps.get-version.outputs.VERSION }}-FOSS.apk
        asset_content_type: application/zip
    - name: Upload APK production OSS
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: ./molly-apk/freeProduction/release/Molly-production-release-unsigned-${{ steps.get-version.outputs.VERSION }}-FOSS.apk
        asset_name: Molly-production-unsigned-${{ steps.get-version.outputs.VERSION }}-FOSS.apk
        asset_content_type: application/zip
