name: Test

on:
  pull_request:
  push:
    paths-ignore:
      - '**/README*.md'
      - '.github/FUNDING.yml'
      - '.github/ISSUE_TEMPLATE/**'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@master

    - name: Increase swap space
      run: |
        sudo fallocate -l 8G /swapB
        sudo chmod 600 /swapB
        sudo mkswap /swapB
        sudo swapon /swapB
        swapon --show

    - name: Build Docker image
      run: docker-compose build
      working-directory: reproducible-builds

    - name: Run tests
      run: docker-compose run test
      working-directory: reproducible-builds

    - name: Archive reports for failed build
      if: "failure()"
      uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: "reproducible-builds/test-reports"
