name: Test

on:
  pull_request:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**/README*.md'
      - '.github/FUNDING.yml'
      - '.github/ISSUE_TEMPLATE/**'

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  wrapper_validation:
    name: Validate Gradle wrapper
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Run wrapper validation
        uses: gradle/wrapper-validation-action@v1

  test:
    name: Run tests
    runs-on: ubuntu-22.04
    env:
      GRADLE_OPTS: "-Dorg.gradle.project.kotlin.compiler.execution.strategy=in-process"

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Run tests
        run: ./gradlew build --no-daemon

      - name: Archive reports for failed tests
        if: "failure()"
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: '*/build/reports'
