name: Test

on:
  pull_request:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**/README*.md'
      - '.github/FUNDING.yml'
      - '.github/ISSUE_TEMPLATE/**'

jobs:
  wrapper_validation:
    name: Validate Gradle wrapper
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Run wrapper validation
        uses: gradle/wrapper-validation-action@master

  test:
    name: Run tests
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Increase swap space
        run: |
          sudo fallocate -l 8G /swapB
          sudo chmod 600 /swapB
          sudo mkswap /swapB
          sudo swapon /swapB
          swapon --show

      - name: Set up builder image
        run: docker-compose build
        working-directory: reproducible-builds

      - name: Run tests
        run: docker-compose run test
        working-directory: reproducible-builds

      - name: Archive reports for failed tests
        if: "failure()"
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: "reproducible-builds/test-reports"
